### ISSUE TITLE
Boolean ?

### ISSUE THREAD

**Issue by Darkyler** [JohanBrunet/GraphLibrary#1]
Why all functions like addEdge/addVertex, remove, .... are returning a boolean and not void ?

**Comment by JohanBrunet** [comment]
They return boolean because we want to see if it worked or not.

**Comment by Darkyler** [comment]
UndirectedEdge res = new UndirectedEdge(""" Vertex[] """);
                         ^
  required: Vertex,Vertex
  found: Vertex[]

But the doc said that the constructor takes an array of Vertex. Is there a problem on the doc ?

**Comment by JohanBrunet** [comment]
No I think the problem might be in the code.
Do you need it right know or can it wait 'till some time later  ?

**Comment by Darkyler** [comment]
Naaa it's fine ! Take your time ;)

**Comment by JohanBrunet** [comment]
Thanks. I'll do it before tomorrow so that you can finish your job before
wednesday  ;)

**Comment by JohanBrunet** [comment]
I updated the code and the doc : replaced the constructor parameters
